### ISSUE TITLE
raft-example: FatalError {fatalErrorMessage = "No log entry at 'newLastAppliedIndex'"}

### ISSUE THREAD

**Issue by stevana** [adjoint-io/raft#58]
As I was trying to clean up the state machine tests, as discussed in #41, I ran into a different problem which the [following](https://github.com/stevana/raft/commit/dac483a67e3517d5d8fe55d4cdb835505284ae0b#diff-aacf0b0e3a8a577b03147244893fde0fR286) generated test reliably reproduces:

```haskell
 Commands
      { unCommands =
          [ Command (SpawnNode 3001) (Set.fromList [ Var 0 ])
          , Command (SpawnNode 3002) (Set.fromList [ Var 1 ])
          , Command (SpawnNode 3000) (Set.fromList [ Var 2 ])
          , Command (Set 14) Set.empty
          , Command Read Set.empty
          , Command Incr Set.empty
          , Command
              (BreakConnection ( 3002 , Reference (Symbolic (Var 1)) ))
              Set.empty
          , Command Incr Set.empty
          , Command Incr Set.empty
          , Command Incr Set.empty
          , Command
              (FixConnection ( 3002 , Reference (Symbolic (Var 1)) )) Set.empty
          , Command
              (BreakConnection ( 3001 , Reference (Symbolic (Var 0)) ))
              Set.empty
          , Command (Set 3) Set.empty
          , Command Incr Set.empty
          , Command Read Set.empty
          , Command Incr Set.empty
          , Command
              (FixConnection ( 3001 , Reference (Symbolic (Var 0)) )) Set.empty
          , Command Read Set.empty
          , Command Incr Set.empty
          , Command Incr Set.empty
          ]
      }
```

To run this test use `stack test --test-arguments="-p test0"`, what you should see is that in one of the node's logs `/tmp/raft-log-300{0,1,2}.txt` it will say:

    [2018-12-03T21:22:15](Debug) <localhost:3001 | Follower>: [Action]: ResetTimeoutTimer ElectionTimeout
    raft-example: FatalError {fatalErrorMessage = "No log entry at 'newLastAppliedIndex'"}

The tests retry sending the `Read` command after the last `FixConnection`, but never get a response (as you can see in `/tmp/raft-log.txt`).

`BreakConnection` and `FixConnection` respectively disable and re-enable the `send` and `recv` syscalls.

**Comment by tdietert** [comment]
Thanks! Looking into it now. 

I think this was actually caused by a failure to implement the instance for `RaftDeleteLog` typeclass for the `RaftFileStoreT` monad transformer in the examples. Perhaps we should add some tests for the user defined instances of the raft typeclasses; their are some "laws" that the instances need to adhere to e.g. the `RaftDeleteLog.deleteLogEntriesFrom` actually needs to delete the logs :sweat:

**Comment by tdietert** [comment]
Please checkout the latest `master` commit and run the tests. I am confident I have fixed the issue; I have run `test0` twice at a full 100 iterations and have observed the failure no longer.

**Comment by stevana** [comment]
I can confirm that `test0` indeed passes now, thanks!
